# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

conda:
  environment: docs/docs_environment.yaml

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    # https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-1143587902
    post_install:
      - cp -r ./notebooks ./docs/notebooks
      - sed 's|./docs/_static|./_static|g' ./README.md > ./docs/README.md
      - sed 's|./docs/_static|./_static|g' ../contributing.md > ./contributing.md

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py