name: sportslabkit_dev_env
channels:
  - defaults
dependencies:
  - python==3.10
  - pip
  - pip:
    - poetry



# name: sportslabkit_dev_env
# channels:
#   - defaults
# dependencies:
#   - python==3.10
#   - pytest==7.1.2
#   - pandas==1.4.2
#   - rich==12.5.1
#   - jupyter==1.0.0
#   - ipywidgets==8.0.4
#   - scikit-learn==1.2.1
#   - gitpython==3.1.30
#   - Cython
#   - Pillow
#   - six
#   - yacs
#   - pytorch
#   - torchvision
#   - pip
#   - pip:
#     - "--editable=."
#     - vidgear[core]==0.3.0
#     - jsonargparse[signatures]==4.20.0
#     - ultralytics
#     - seedir
#     - py-cpuinfo
#     - black
#     - ffmpeg-python==0.2.0
#     - pytorch_lightning
#     - einops==0.6.0
#     - protobuf==3.20.0
#     - ipython==8.5.0
#     - labelbox==3.35.0
#     - filterpy==1.4.5
#     - python-dotenv==0.21.1
#     - opencv-contrib-python
#     - numpy==1.22.4
#     - scikit-video==1.1.11
#     - poetry==1.3.1
#     - tensorboard==2.11.2
#     - docformatter==1.5.1
#     - scipy==1.8.1
#     - kaggle==1.5.12
#     - mypy==0.960
#     - optuna==3.1.1
#     - networkx==3.1
#     - fire==0.5.0
#     - ndjson==0.3.1
#     - mplsoccer==1.1.10
#     - loguru==0.6.0
#     - pyroma==4.0
#     - omegaconf==2.2.2
#     - types-python-dateutil==2.8.17
#     - motpy==0.0.10
#     - papermill==2.4.0
#     - pytest-xdist==3.3.1