name: ❓ Question
description: Ask a SoccerTrack question
# title: " "
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for asking a SoccerTrack ❓ Question!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/AtomScott/SoccerTrack/issues) and [discussions](https://github.com/AtomScott/SoccerTrack/discussions) to see if a similar question already exists.
      options:
        - label: >
            I have searched the YOLOv5 [issues](https://github.com/AtomScott/SoccerTrack/issues) and [discussions](https://github.com/AtomScott/SoccerTrack/discussions) and found no similar questions.
          required: true

  - type: textarea
    attributes:
      label: Question
      description: What is your question?
      placeholder: |
        💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?