det_model_name: yolov5
det_model_repo: external/yolov5
det_model_ckpt: models/yolov5/yolov5x.pt
# path_to_csv: 
path_to_mp4: ./soccertrack/datasets/wide_view/videos/F_20200220_1_0000_0030.mp4
# path_to_csv: ./soccertrack/datasets/top_view/annotations/D_20220220_1_0000_0030.csv
# path_to_mp4: ./soccertrack/datasets/top_view/videos/D_20220220_1_0000_0030.mp4
log_level: DEBUG
save_path: outputs/yolov5/
save_results: false
save_video: true
save_video_kwargs: {}
device: cpu
batch_size: 4