name: soccertrack_docs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - sphinx
  - pip:
    - furo
    - sphinx==6.1.3
    - sphinx-autoapi==2.0.0
    - sphinx-autodoc-typehints==1.18.3
    - nbsphinx==0.8.9
    - m2r2==0.3.2
