name: MyPy check
on:
  push:

jobs:
  mypy-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Run MyPy
      uses: jpetrucciani/mypy-check@master
      with:
        mypy_flags: '--config-file pyproject.toml'
