name: Publish to Test PyPI on Develop Update

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install poetry
      run: pip install poetry

    - name: Configure Test PyPI and Token
      run: |
        poetry config repositories.test-pypi https://test.pypi.org/legacy/
        poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_API_TOKEN }}

    - name: Build and publish to Test PyPI
      run: |
        poetry build
        poetry publish --repository test-pypi
