name: Publish to Test PyPI on Develop Update

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install poetry
      run: pip install poetry

    - name: Build and publish to Test PyPI
      run: |
        poetry build
        poetry publish --repository-url https://test.pypi.org/legacy/ -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }}
